import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { svgStyles } from "./svg-styles.ts";

const ENTRY = new URL("./runtime/index.ts", import.meta.url).pathname;
const OUT = new URL("./runtime.bundle.ts", import.meta.url).pathname;

async function main() {
  const result = await Bun.build({
    entrypoints: [ENTRY],
    minify: true,
    target: "browser",
    format: "iife",
  });
  if (!result.success) {
    throw new Error(`Runtime build failed: ${result.logs.map(log => log.message).join("; ")}`);
  }
  const output = result.outputs[0];
  if (!output) throw new Error("Runtime build did not produce an output file");
  const js = await output.text();
  const shell = `<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Widget</title>
<style>
*{box-sizing:border-box}
:root{color-scheme:light dark}
body{margin:0;padding:1rem;font-family:system-ui,-apple-system,sans-serif;background:transparent;color:var(--color-text-primary,#111)}
@keyframes _ompGenerativeUiFadeIn{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}
${svgStyles}
</style>
</head><body><div id="root"></div><script>${js}</script></body></html>`;
  const hash = createHash("sha256").update(shell).digest("hex").slice(0, 12);
  const escaped = shell.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  await writeFile(OUT, `// AUTO-GENERATED by build.mjs — do not edit by hand.\n// Hash: ${hash}\n\nexport const RUNTIME_VERSION = "${hash}";\nexport const RUNTIME_HTML = \`${escaped}\`;\n`, "utf8");
  console.log(`built runtime.bundle.ts — ${(Buffer.byteLength(shell, "utf8") / 1024).toFixed(1)} KB, hash ${hash}`);
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
