import { createHash } from "node:crypto";

const result = await Bun.build({
  entrypoints: [new URL("./runtime/main.ts", import.meta.url).pathname],
  target: "browser",
  minify: true,
});
if (!result.success) throw new Error("runtime build failed");
const js = await result.outputs[0].text();
const hash = createHash("sha256").update(js).digest("hex").slice(0, 12);
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Subagent Preview</title><style>${css()}</style></head><body><div id="root"></div><script>${js}</script></body></html>`;
await Bun.write(new URL("./runtime.bundle.ts", import.meta.url), `// AUTO-GENERATED by build.mjs — do not edit by hand.\nexport const RUNTIME_VERSION = ${JSON.stringify(hash)};\nexport const RUNTIME_HTML = ${JSON.stringify(html)};\n`);

function css() {
  return `:root{color-scheme:light dark}*{box-sizing:border-box}body{margin:0;padding:12px;font-family:system-ui,-apple-system,sans-serif;background:transparent;color:var(--color-text-primary,#111)}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:12px}.summary button,.agent{border:1px solid rgba(128,128,128,.25);border-radius:10px;padding:10px;background:transparent;color:inherit}.summary span{font-size:22px;font-weight:600;display:block}.summary label,.meta,.empty{color:var(--color-text-secondary,#666);font-size:13px}.agents{display:grid;gap:8px}.agent header{display:flex;justify-content:space-between;gap:8px;cursor:pointer}.agent pre{white-space:pre-wrap;margin:8px 0 0;font-size:12px}.entry{font-size:13px;border-top:1px solid rgba(128,128,128,.2);padding-top:6px;margin-top:6px}`;
}
