import { createHash } from "node:crypto";

const result = await Bun.build({
  entrypoints: [new URL("./runtime/entry.ts", import.meta.url).pathname],
  target: "browser",
  minify: true,
});
if (!result.success) throw new Error("runtime build failed");
const js = await result.outputs[0].text();
const hash = createHash("sha256").update(js).digest("hex").slice(0, 12);
const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Subagent Preview</title><style>${css()}</style></head><body><div id="root"></div><script>${js}</script></body></html>`;
await Bun.write(new URL("./runtime.bundle.ts", import.meta.url), `// AUTO-GENERATED by build.mjs — do not edit by hand.\nexport const RUNTIME_VERSION = ${JSON.stringify(hash)};\nexport const RUNTIME_HTML = ${JSON.stringify(html)};\n`);

function css() {
  return `
:root{
  color-scheme:light dark;
  --sp-text:var(--color-text-primary,CanvasText);
  --sp-muted:var(--color-text-secondary,GrayText);
  --sp-bg:var(--color-background,Canvas);
  --sp-card:color-mix(in srgb,Canvas 92%,CanvasText 8%);
  --sp-card-strong:color-mix(in srgb,Canvas 84%,CanvasText 16%);
  --sp-border:color-mix(in srgb,CanvasText 18%,transparent);
  --sp-border-strong:color-mix(in srgb,CanvasText 30%,transparent);
  --sp-accent:color-mix(in srgb,Highlight 74%,CanvasText 8%);
  --sp-accent-soft:color-mix(in srgb,Highlight 16%,transparent);
  --sp-shadow:color-mix(in srgb,CanvasText 12%,transparent);
}
*{box-sizing:border-box}
body{margin:0;min-height:100vh;padding:16px;font-family:Avenir Next,ui-rounded,ui-sans-serif,system-ui,sans-serif;background:radial-gradient(circle at top left,color-mix(in srgb,Highlight 12%,transparent),transparent 34rem),linear-gradient(180deg,color-mix(in srgb,Canvas 96%,CanvasText 4%),var(--sp-bg));color:var(--sp-text)}
button{font:inherit;color:inherit}
.hero{display:flex;align-items:stretch;justify-content:space-between;gap:12px;margin-bottom:12px;padding:14px;border:1px solid var(--sp-border);border-radius:18px;background:linear-gradient(135deg,var(--sp-card),color-mix(in srgb,var(--sp-card) 78%,Highlight 8%));box-shadow:0 16px 42px var(--sp-shadow)}
.eyebrow{margin:0 0 4px;color:var(--sp-muted);font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}
h1{margin:0;font-size:24px;line-height:1.05;letter-spacing:-.04em}
.lede{margin:6px 0 0;color:var(--sp-muted);font-size:13px}
.follow-toggle,.summary button,.copy-button{border:1px solid var(--sp-border);border-radius:12px;background:color-mix(in srgb,var(--sp-card) 86%,transparent);cursor:pointer;transition:transform .14s ease,border-color .14s ease,background .14s ease}
.follow-toggle:hover,.summary button:hover,.copy-button:hover{transform:translateY(-1px);border-color:var(--sp-border-strong)}
.follow-toggle{min-width:96px;padding:10px;text-align:left}
.follow-state,.summary button>span:first-child{display:block;font-size:22px;font-weight:800;letter-spacing:-.04em}
.follow-label,.chip-label,.meta dt,.console-label,.entry-meta{color:var(--sp-muted);font-size:11px;font-weight:750;letter-spacing:.08em;text-transform:uppercase}
.follow-toggle.is-on,.summary button[aria-pressed="true"]{border-color:var(--sp-accent);background:var(--sp-accent-soft)}
.summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(96px,1fr));gap:8px;margin-bottom:12px}
.summary button{padding:10px;text-align:left}
.agents{display:grid;gap:10px}
.agent{min-width:0;overflow:hidden;border:1px solid var(--sp-border);border-radius:18px;background:var(--sp-card);box-shadow:0 10px 30px color-mix(in srgb,var(--sp-shadow) 70%,transparent)}
.agent-header{border-bottom:1px solid var(--sp-border)}
.agent-toggle{position:relative;display:grid;width:100%;grid-template-columns:1fr auto;gap:4px 10px;align-items:center;border:0;padding:12px 14px;background:transparent;text-align:left;cursor:pointer}
.agent-title{font-weight:800;letter-spacing:-.02em}
.agent-subtitle{grid-column:1;color:var(--sp-muted);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.status-pill{grid-row:1 / span 2;grid-column:2;align-self:center;border:1px solid var(--sp-border);border-radius:999px;padding:4px 9px;background:color-mix(in srgb,CanvasText 7%,transparent);font-size:12px;font-weight:800;text-transform:capitalize}
.agent[data-status="running"] .status-pill,.agent[data-status="pending"] .status-pill{border-color:var(--sp-accent);background:var(--sp-accent-soft)}
.agent-body{display:grid;gap:10px;padding:12px 14px 14px}
.meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(92px,1fr));gap:8px;margin:0}
.meta div{min-width:0;border:1px solid var(--sp-border);border-radius:12px;padding:8px;background:color-mix(in srgb,var(--sp-card-strong) 58%,transparent)}
.meta dt,.meta dd{margin:0}
.meta dd{margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:700}
.copy-button{justify-self:start;padding:6px 10px}
.console-label{margin:0}
.console pre{white-space:pre-wrap;margin:6px 0 0;max-height:120px;overflow:auto;border:1px solid var(--sp-border);border-radius:12px;padding:10px;background:color-mix(in srgb,CanvasText 7%,transparent);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;color:var(--sp-text)}
.transcript{max-height:320px;overflow:auto;overscroll-behavior:contain;border:1px solid var(--sp-border);border-radius:14px;background:color-mix(in srgb,var(--sp-bg) 72%,transparent);scrollbar-gutter:stable}
.entry{display:grid;gap:4px;padding:10px 12px;border-top:1px solid var(--sp-border)}
.entry:first-child{border-top:0}
.entry-meta{display:flex;gap:8px;align-items:center}
.entry-meta em{font-style:normal;color:var(--sp-text)}
.entry-text{white-space:pre-wrap;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;line-height:1.45}
.entry[data-kind="tool_result"][class*="tool_result"] .entry-text,.entry.tool_result .entry-text{color:color-mix(in srgb,var(--sp-text) 84%,var(--sp-muted))}
.empty{margin:0;color:var(--sp-muted);font-size:13px}
.transcript-empty{padding:12px}
@media (max-width:560px){body{padding:10px}.hero{flex-direction:column}.follow-toggle{width:100%}.agent-toggle{grid-template-columns:1fr}.status-pill{grid-column:1;grid-row:auto;justify-self:start}}
`.replaceAll(/\s+/g, " ").trim();
}
